# Format: {A}_{S}
# A = algorithm name, lowercase, without space (must match the src/*.c and src/*.h name)
# S = waiting strategy. original = hardcoded in the algorithm (see README), otherwise spinlock/spin_then_park/park

ALGORITHMS=mcs_spinlock      \
mcsepfl_original             \
mcs_spin_then_park           \
mcstp_original               \
spinlock_original            \
spinlockepfl_original        \
malthusian_spinlock          \
malthusian_spin_then_park    \
ttas_original                \
ttasepfl_original            \
ticket_original              \
ticketepfl_original          \
clh_spinlock                 \
clh_spin_then_park           \
clhepfl_original             \
backoff_original             \
empty_original               \
pthreadinterpose_original    \
pthreadadaptive_original     \
concurrency_original	     \
htlockepfl_original          \
alockepfl_original           \
hmcs_original                \
hyshmcs_original			 \
cbomcs_spinlock 			 \
cbomcs_spin_then_park 		 \
cptltkt_original 			 \
ctkttkt_original 			 \
partitioned_original         \
mutexee_original
